#! /bin/bash
#
read -p "Sisestage kataloogi nimi mida tahad pakkida: " katalooginimi
baasnimi="$(basename $katalooginimi)"
asukoht="/home/user/skriptimine/praks4a/backup/$baasnimi.backup.tar.gz"
tar -zcvf $asukoht $katalooginimi
echo "Kataloogi $katalooginimi backup'i nimi on $baasnimi.backup.tar.gz ja ta asub $asukoht"
#
