#!/bin/bash
#
read -p "Sisestage palun kuu: " kuu
if test $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12
then
	echo "On talv"
elif test $kuu -ge 3 -a $kuu -lt 5
then
	echo "On kevad"
elif test $kuu -ge 6 -a $kuu -lt 8
then
	echo "On suvi"
elif test $kuu -ge 9 -a $kuu -lt 11
then
	echo "On sügis"
elif test $kuu -ge 11
then
	echo "On sügis"
elif test $kuu -ge 2
then
	echo "On talv"
elif test $kuu -ge 5
then
	echo "On kevad"
elif test $kuu -ge 8
then
	echo "On suvi"
else
	echo "Vigane sisend"
fi
#
