#!/bin/bash
#
read -p "Sisestage aja väärtus: " aeg
read -p "Sisestage kasutaja nimi: " nimi

if [[ $aeg -ge 6 ]] && [[ $aeg -le 11 ]]
then
	echo "Tere hommikust, $nimi!"
elif [[ $aeg -ge 12 ]] && [[ $aeg -le 17 ]]
then
	echo "Tere päevast, $nimi!"
elif [[ $aeg -ge 18 ]] && [[ $aeg -le 21 ]]
then
	echo "Tere õhtust, $nimi!"
elif [[ $aeg -ge 22 ]] && [[ $aeg -le 24 ]]
then
	echo "Head ööd, $nimi!"
elif [[ $aeg -ge 1 ]] && [[ $aeg -le 5 ]]
then
	echo "Head ööd, $nimi!"
fi
#
