#!/bin/bash
#
read -p "Sisesta suvaline täisarv: " numbrid
if [ $numbrid -gt 0 ]
	numbrid=$(($numbrid * -1))

summa=0
while [ $numbrid -ne 0 ]
do
	jaak=$(($numbrid % 10))
	summa=$(($summa + $jaak))
	numbrid=$(($numbrid / 10))
fi
done
echo "Arvu $a numbrite summa on $summa"
#
